Models/Database/ProductHelper.cs
using System.Collections.Generic;

namespace pwt_0x01_ng.Models.Database
{
	public static class ProductHelper
	{
		public static IList<Product> GenerateProduct()
		{
			IList<Product> products = new List<Product>()
			{
				new Product() { Name="a", Price=0, Description="aaaa", ImageSrc = "/images/banner1.svg", ImageAlt = "ASP.NET", Similar = {}},
				new Product() { Name="b", Price=1, Description="bbbb", ImageSrc = "/images/banner2.svg", ImageAlt = "ASP.NET", Similar = {}},
				new Product() { Name="c", Price=2, Description="cccc", ImageSrc = "/images/banner3.svg", ImageAlt = "ASP.NET", Similar = {}},
				new Product() { Name="d", Price=3, Description="dddd", ImageSrc = "/images/ms_loves_linux.jpeg", ImageAlt = "msloveslinux", Similar = {}}
					};
			return products;
		}
	}
}

Models/Product.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using pwt_0x01_ng.Models.Validation;

namespace pwt_0x01_ng.Models
{
	[Table("Product")]
	public class Product : Entity
	{
		[Required]
		public string Name { get; set; }
		[Required]
		public int Price { get; set; }
		[Required]
		public string Description { get; set; }
		[FileTypeAttr("image")]
		[NotMapped]
		public IFormFile Image { get; set; }
		[StringLength(255)]
		public string ImageSrc { get; set; }
		[Required]
		[StringLength(50, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 1)]
		public string ImageAlt { get; set; }
		[NotMapped]
		public IList<SimilarProduct> Similar { get; set; }
		[NotMapped]
		public bool Selected { get; set; }
	}
}

Models/ProductViewModel.cs
using System.Collections.Generic;

namespace pwt_0x01_ng.Models
{
	public class ProductViewModel
	{
		public IList<Product> Products { get; set; }
	}
}

Areas/Admin/Controllers/ProductController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using pwt_0x01_ng.Models;
using pwt_0x01_ng.Models.Database;
using pwt_0x01_ng.Models.Identity;
using System.Collections.Generic;

namespace pwt_0x01_ng.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = nameof(Roles.Admin) + "," + nameof(Roles.Manager))]
	public class ProductController : Controller
	{
		IWebHostEnvironment hosting_env;
		readonly DBContext dbctx;

		public ProductController(DBContext dbctx, IWebHostEnvironment hosting_env){
			this.dbctx = dbctx;
			this.hosting_env = hosting_env;
		}

		public async Task <IActionResult> Select()
		{
			ProductViewModel product = new ProductViewModel();
			product.Products = await dbctx.Product.ToListAsync();
			return View(product);
		}

		public async Task<IActionResult> Create()
		{
			ProductViewModel product = new ProductViewModel();
			product.Products = await dbctx.Product.ToListAsync();
			ViewData["prods"] = product.Products;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(Product product)
		{
			if (ModelState.IsValid) {
				MegaUpload mega_upload = new MegaUpload(hosting_env.WebRootPath, "products", "image");
				if ((product.ImageSrc = await mega_upload.DoMegaUpload(product.Image)) != string.Empty){/* all good here */};

				dbctx.Product.Add(product);
				await dbctx.SaveChangesAsync();
				return RedirectToAction(nameof(Select));
			} else {
				ViewData["Message"] = "error creating Product";
				return View(product);
			}
		}

		public async Task<IActionResult> Edit(int id)
		{
			ProductViewModel product = new ProductViewModel();
			product.Products = await dbctx.Product.ToListAsync();
			ViewData["prods"] = product.Products;

			Product item = dbctx.Product.Where(p_item => p_item.id == id).FirstOrDefault();
			if (item != null)
			{
				IList<Similar> s = await dbctx.Similar.Where(p_item => p_item.prod_id == id).ToListAsync();
				IList<SimilarProduct> similar = new List<SimilarProduct>();
				foreach (var prod in product.Products) {
					SimilarProduct sp = new SimilarProduct();
					sp.id = prod.id;
					sp.Selected = prod.Selected;
					similar.Add(sp);
				}
				foreach (var s_item in s)
				{
					var prodpls = await dbctx.Product.Where(p_item => p_item.id == s_item.similar_prod_id).FirstOrDefaultAsync();
					if(prodpls != null){
						for (int i = 0; i < similar.Count; i++)
						{
							if(similar[i].id == prodpls.id){
								similar[i].Selected = true;
							}
						}
					}
				}
				item.Similar = similar;
				ViewData["ImageSrc"] = new SelectList(dbctx.Product, "ImageSrc", item.ImageSrc);
				return View(item);
			}
			else
			{
				return NotFound();
			}
		}

		[HttpPost]
		public async Task<IActionResult> Edit(Product product)
		{
			Product item = dbctx.Product.Where(p_item => p_item.id == product.id).FirstOrDefault();

			if (item != null)
			{
				if (ModelState.IsValid) {
					item.id = product.id;
					item.Name = product.Name;
					item.Price = product.Price;
					item.Description = product.Description;
					item.ImageAlt = product.ImageAlt;

					MegaUpload mega_upload = new MegaUpload(hosting_env.WebRootPath, "products", "image");
					if ((product.ImageSrc = await mega_upload.DoMegaUpload(product.Image)) != string.Empty){
						item.ImageSrc = product.ImageSrc;
					}

					if (product.Similar != null) {
						IList<SimilarProduct> similar = new List<SimilarProduct>();
						foreach (var prod in product.Similar) {
							SimilarProduct sp = new SimilarProduct();
							sp.id = prod.id;
							sp.Selected = prod.Selected;
							similar.Add(sp);
						}
						if(similar.Count > 0){
							foreach (var prod in similar)
							{
								Similar s = dbctx.Similar.Where(p_item => p_item.prod_id == item.id && p_item.similar_prod_id == prod.id).FirstOrDefault();
								if(prod.Selected){
									if (s == null) {
										s = new Similar();
										s.prod_id = item.id;
										s.similar_prod_id = prod.id;
										dbctx.Similar.Add(s);
									}
								} else {
									if (s != null) {
										dbctx.Similar.Remove(s);
									}
								}
							}
						}
					}

					await dbctx.SaveChangesAsync();
					return RedirectToAction(nameof(Select));
				}
				var errors = ModelState.Values.SelectMany(v => v.Errors);
				ViewData["Message"] = "error editing Product";
				return View(item);
			}
			else
			{
				return NotFound();
			}
		}

		public async Task <IActionResult> Delete(int id)
		{
			Product item = dbctx.Product.Where(p_item => p_item.id == id).FirstOrDefault();
			if (item != null)
			{
				dbctx.Product.Remove(item);
				await dbctx.SaveChangesAsync();
				return RedirectToAction(nameof(Select));
			}
			else
			{
				return NotFound();
			}
		}
	}
}

Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using pwt_0x01_ng.Models;
using pwt_0x01_ng.Models.Database;

namespace pwt_0x01_ng.Controllers
{
	public class ProductsController : Controller
	{
		readonly DBContext dbctx;

		public ProductsController(DBContext dbctx){
			this.dbctx = dbctx;
		}
		public async Task<IActionResult> Detail(int id){
			Product p = await dbctx.Product.Where(p_item => p_item.id == id).FirstOrDefaultAsync();
			if (p == null) return NotFound();

			IList<Similar> s = await dbctx.Similar.Where(p_item => p_item.prod_id == id).ToListAsync();
			IList<Product> similar = new List<Product>();
			if (s != null) {
				foreach (var s_item in s) {
					var prod = await dbctx.Product.Where(p_item => p_item.id == s_item.similar_prod_id).FirstOrDefaultAsync();
					if (prod != null) {
						similar.Add(prod);
					}
				}
			}

			if (similar.Count > 0) {
				ViewData["similar"] = similar;
			}
			return View(p);
		}
	}
}

Views/Products/Detail.cshtml
@model pwt_0x01_ng.Models.Product

@{
	ViewData["Title"] = "Detail - " + @Model.Name;
}
<h2>Detail</h2>
<h3>@ViewData["Message"]</h3>

<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<h1 class="my-4">@Model.Name</h1>
			<div class="list-group">
				<a href="#" class="list-group-item active">Category 1</a>
				<a href="#" class="list-group-item">Category 2</a>
				<a href="#" class="list-group-item">Category 3</a>
			</div>
		</div><!-- /.col-lg-3 -->

		<div class="col-lg-9">
			<div class="card mt-4">
				<img class="card-img-top img-fluid img-responsive" src="@Model.ImageSrc" alt="@Model.ImageAlt">
				<div class="card-body">
					<h3 class="card-title">@Model.Name</h3>
					<h4>@Model.Price €</h4>
					<p class="card-text">@Model.Description</p>
				</div>
			</div><!-- /.card -->

			<div class="card card-outline-secondary my-4">
				<div class="card-body">
					<hr>
					<input type="button" id="add_to_order" class="btn btn-primary" value="Add to order" onclick="Buy(@Model.id,'@Url.Action("AddOrderItemsToSession", "CustomerOrderNotCart", new { Area = "Customer" })', '#price_total', '@System.Globalization.CultureInfo.CurrentCulture.Name')" />
				</div>
			</div><!-- /.card -->
			<partial name="_partial_SimilarProducts"/>
		</div><!-- /.col-lg-9 -->
	</div>
</div>

Views/Products/_partial_Products.cshtml
<!-- Page Content -->
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<h1 class="my-4">Products</h1>
			<div class="list-group">
				<a href="#" class="list-group-item">Category 1</a>
				<a href="#" class="list-group-item">Category 2</a>
				<a href="#" class="list-group-item">Category 3</a>
			</div>
		</div><!-- /.col-lg-3 -->
		<div class="col-lg-9">
		<div class="row">
		@{
			if (Model != null && Model.Products.Count > 0){
				for(int i = 0; i < Model.Products.Count; i++){
					<div id="prod_card" class="col-lg-4 col-md-6 mb-4">
						<div class="card h-100">
							<a asp-area="" asp-controller="Products" asp-action="Detail" asp-route-id="@Model.Products[i].id"><img class="card-img-top img-responsive" id="prod_list_img" src="@Model.Products[i].ImageSrc" alt="@Model.Products[i].ImageAlt"></a>
							<div class="card-body">
								<h4 class="card-title">
									<a asp-area="" asp-controller="Products" asp-action="Detail" asp-route-id="@Model.Products[i].id">@Model.Products[i].Name</a>
								</h4>
								<h5>@Model.Products[i].Price €</h5>
								<p class="card-text">@Model.Products[i].Description</p>
							</div>
							<div class="card-footer">
								<small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
							</div>
						</div>
					</div>
				}
			} else {
				<h3 class="text-info"><code>we apologise, no products are available at the moment.</code></h3>
			}
		}
		</div><!-- /.row -->
		</div><!-- /.col-lg-9 -->
	</div><!-- /.row -->
</div><!-- /.container -->

Views/Products/_partial_SimilarProducts.cshtml
@model pwt_0x01_ng.Models.Product
@{
	IList<Product> similar;
	similar = (IList<Product>) ViewData["similar"];
}
<div class="container">
	<div class="col-lg-9">
		<div class="row">
			@if (similar != null && similar.Count > 0) {
				<div class="col-lg-12 col-md-12">
					<div class="col-lg-4 col-md-4">
						<hr>
						<label>Similar products</label>
					</div>
				</div>
				int count_till = 3;
				if (similar.Count < 3) count_till = similar.Count;
				@for (int i = 0; i < count_till; i++) {
					<div id="prod_card" class="col-lg-4 col-md-6 mb-4">
						<div class="card h-100">
							<a asp-area="" asp-controller="Products" asp-action="Detail" asp-route-id="@similar[i].id"><img class="card-img-top img-responsive" id="prod_list_img" src="@similar[i].ImageSrc" alt="@similar[i].ImageAlt"></a>
							<div class="card-body">
								<label><a asp-area="" asp-controller="Products" asp-action="Detail" asp-route-id="@similar[i].id">@similar[i].Name</a></label>
								<div class="card-text">@similar[i].Description</div>
							</div>
							<div class="card-footer">
								<div class="text-muted">@similar[i].Price €</div>
							</div>
						</div>
					</div>
				}
			}
		</div>
	</div>
</div>